### ISSUE TITLE
My bot is not starting someone help me 

### ISSUE THREAD

**Issue by YeetDevDiscord** [Focus04/focus#13]
```
internal/validators.js:124
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Module.require (internal/modules/cjs/loader.js:967:3)
    at require (internal/modules/cjs/helpers.js:92:18)
    at loadStore (C:\Users\sayad\OneDrive\Desktop\090620\REAA\Discord utility bot\node_modules\keyv\src\index.js:18:15)
    at new Keyv (C:\Users\sayad\OneDrive\Desktop\090620\REAA\Discord utility bot\node_modules\keyv\src\index.js:39:22)
    at Object.<anonymous> (C:\Users\sayad\OneDrive\Desktop\090620\REAA\Discord utility bot\Commands\Debug\serversettings.js:3:28)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
**this is what it says when i try and start the bot**

**Comment by YeetDevDiscord** [comment]
@Focus04 can you help

**Comment by YeetDevDiscord** [comment]
issue is fixed
