### ISSUE TITLE
The bot isnt starting

### ISSUE THREAD

**Issue by YeetDevDiscord** [Focus04/focus#14]
```
(node:22384) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'get' of undefined
    at C:\Users\sayad\OneDrive\Desktop\Dynomixcs utils\Events\Init\ready.js:15:41
    at Map.forEach (<anonymous>)
    at module.exports (C:\Users\sayad\OneDrive\Desktop\Dynomixcs utils\Events\Init\ready.js:14:23)
    at Client.emit (events.js:375:28)
    at WebSocketManager.triggerClientReady (C:\Users\sayad\OneDrive\Desktop\Dynomixcs utils\node_modules\discord.js\src\client\websocket\WebSocketManager.js:431:17)
    at WebSocketManager.checkShardsReady (C:\Users\sayad\OneDrive\Desktop\Dynomixcs utils\node_modules\discord.js\src\client\websocket\WebSocketManager.js:415:10)
    at WebSocketShard.<anonymous> (C:\Users\sayad\OneDrive\Desktop\Dynomixcs utils\node_modules\discord.js\src\client\websocket\WebSocketManager.js:197:14)   
    at WebSocketShard.emit (events.js:375:28)
    at WebSocketShard.checkReady (C:\Users\sayad\OneDrive\Desktop\Dynomixcs utils\node_modules\discord.js\src\client\websocket\WebSocketShard.js:475:12)      
    at WebSocketShard.onPacket (C:\Users\sayad\OneDrive\Desktop\Dynomixcs utils\node_modules\discord.js\src\client\websocket\WebSocketShard.js:447:16)        
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22384) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate 
the Node.js process with a non-zero exit code.
(node:22384) UnhandledPromiseRejectionWarning: TypeError: punishments.get is not a function
    at Timeout._onTimeout (C:\Users\sayad\OneDrive\Desktop\Dynomixcs utils\Events\Init\ready.js:21:38)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
(node:22384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

_**This is what i get when i try and start the bot**_

**Comment by YeetDevDiscord** [comment]
@Focus04 can you help

**Comment by Focus04** [comment]
Looks like the bot can't connect to the database. Read step 4 in the documentation and make sure you did everything right. If you encounter further difficulties, join my [Discord server](https://discord.gg/6CGkUm6).

**Comment by stranzero** [comment]
same
