### ISSUE TITLE
pls help

### ISSUE THREAD

**Issue by python-hmv** [Focus04/focus#15]
ternal/validators.js:124throw new ERR_INVALID_ARG_TYPE(name, 'string', value);^TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefinedat validateString (internal/validators.js:124:11)at Module.require (internal/modules/cjs/loader.js:954:3)at require (internal/modules/cjs/helpers.js:92:18)at loadStore (/home/container/node_modules/keyv/src/index.js:18:15)at new Keyv (/home/container/node_modules/keyv/src/index.js:39:22)at Object.<anonymous> (/home/container/Commands/Debug/serversettings.js:3:28)at Module._compile (internal/modules/cjs/loader.js:1072:14)at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)at Module.load (internal/modules/cjs/loader.js:937:32)at Function.Module._load (internal/modules/cjs/loader.js:778:12) {code: 'ERR_INVALID_ARG_TYPE'}

**Comment by iiAlanii** [comment]
> ternal/validators.js:124throw new ERR_INVALID_ARG_TYPE(name, 'string', value);^TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefinedat validateString (internal/validators.js:124:11)at Module.require (internal/modules/cjs/loader.js:954:3)at require (internal/modules/cjs/helpers.js:92:18)at loadStore (/home/container/node_modules/keyv/src/index.js:18:15)at new Keyv (/home/container/node_modules/keyv/src/index.js:39:22)at Object. (/home/container/Commands/Debug/serversettings.js:3:28)at Module._compile (internal/modules/cjs/loader.js:1072:14)at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)at Module.load (internal/modules/cjs/loader.js:937:32)at Function.Module._load (internal/modules/cjs/loader.js:778:12) {code: 'ERR_INVALID_ARG_TYPE'}

This has been fixed in #14
